// Display metadata and authoring rules for every node type.
// Single source of truth shared by NodeCard, AddNodeForm, and Legend.

import type { NodeType } from "./types";

export interface NodeMeta {
  label: string; // e.g. "ARGUMENT (SUPPORT)"
  icon: string; // single glyph / emoji
  color: string; // hex, used for the node's accent
  description: string; // short "what it is"
  prompt: string; // input prompt when authoring
  placeholder: string; // example text for the input
  terminal: boolean;
}

export const NODE_META: Record<NodeType, NodeMeta> = {
  question: {
    label: "QUESTION",
    icon: "?",
    color: "#0066cc",
    description: "An inquiry, issue, or topic to explore or answer.",
    prompt: "What question do you want to explore?",
    placeholder: "Should you pull the lever?",
    terminal: false,
  },
  position: {
    label: "POSITION",
    icon: "◆",
    color: "#666666",
    description: "A candidate answer, stance, or claim.",
    prompt: "What is your position / answer?",
    placeholder: "Yes, pull the lever",
    terminal: false,
  },
  "argument-support": {
    label: "ARGUMENT (SUPPORT)",
    icon: "+",
    color: "#00aa00",
    description: "Reasoning that backs up a position.",
    prompt: "What is your reasoning?",
    placeholder: "Saving more lives is better",
    terminal: false,
  },
  "argument-attack": {
    label: "ARGUMENT (ATTACK)",
    icon: "−",
    color: "#cc0000",
    description: "Reasoning that challenges or undermines a position.",
    prompt: "What is your objection?",
    placeholder: "But pulling the lever makes you a killer",
    terminal: false,
  },
  "evidence-empirical": {
    label: "EVIDENCE (EMPIRICAL)",
    icon: "📊",
    color: "#008080",
    description: "Data, studies, statistics, or measurable facts.",
    prompt: "What data or study supports this?",
    placeholder: "Studies show 78% of refugees become self-sufficient...",
    terminal: false,
  },
  "evidence-anecdotal": {
    label: "EVIDENCE (ANECDOTAL)",
    icon: "📖",
    color: "#ff8800",
    description: "Personal stories, examples, or case studies.",
    prompt: "What example or story illustrates this?",
    placeholder: "I knew a refugee who became a doctor...",
    terminal: false,
  },
  assumption: {
    label: "ASSUMPTION",
    icon: "⚙",
    color: "#9900cc",
    description: "An unstated premise an argument relies on.",
    prompt: "What assumption underlies this?",
    placeholder: "This assumes we can predict outcomes",
    terminal: false,
  },
  definition: {
    label: "DEFINITION",
    icon: "📝",
    color: "#4B0082",
    description: "Clarifies what a term or concept means.",
    prompt: "How do you define this term?",
    placeholder: "By 'justice' I mean...",
    terminal: false,
  },
  caveat: {
    label: "CAVEAT / EXCEPTION",
    icon: "⚠",
    color: "#ffcc00",
    description: "A limitation, condition, or exception to a claim.",
    prompt: "What is the limitation or exception?",
    placeholder: "This only applies when...",
    terminal: false,
  },
  clarification: {
    label: "CLARIFICATION",
    icon: "💬",
    color: "#00bcd4",
    description: "Elaboration that removes ambiguity about your position.",
    prompt: "What do you need to clarify?",
    placeholder: "I don't mean that all punishment is wrong",
    terminal: false,
  },
  "counter-argument": {
    label: "COUNTER-ARGUMENT",
    icon: "⚡",
    color: "#ff0000",
    description: "A direct response presenting an opposing view.",
    prompt: "What is the counter-argument?",
    placeholder: "But you're ignoring that inaction has consequences",
    terminal: false,
  },
  objection: {
    label: "OBJECTION",
    icon: "✗",
    color: "#8B0000",
    description: "A challenge or concern with a position or argument.",
    prompt: "What is the objection?",
    placeholder: "This ignores the psychological trauma",
    terminal: false,
  },
  rebuttal: {
    label: "REBUTTAL",
    icon: "✓",
    color: "#006400",
    description: "A response defending against an objection.",
    prompt: "How do you respond to this objection?",
    placeholder: "But the trauma is outweighed by saving 5 lives",
    terminal: false,
  },
  analogy: {
    label: "ANALOGY",
    icon: "🔄",
    color: "#FF00FF",
    description: "A comparison to a similar situation to illustrate a point.",
    prompt: "What analogy illustrates this?",
    placeholder: "This is like a doctor choosing between patients",
    terminal: false,
  },
  "thought-experiment": {
    label: "THOUGHT EXPERIMENT",
    icon: "🧠",
    color: "#22c55e",
    description: "A hypothetical scenario that tests intuitions.",
    prompt: "What hypothetical scenario tests this?",
    placeholder: "Imagine you had to choose between your child or 5 strangers",
    terminal: false,
  },
  "related-concept": {
    label: "RELATED CONCEPT",
    icon: "🔗",
    color: "#8B4513",
    description: "A connection to another relevant idea or principle.",
    prompt: "What concept does this relate to?",
    placeholder: "This connects to the principle of double effect",
    terminal: false,
  },
  "logical-fallacy": {
    label: "LOGICAL FALLACY",
    icon: "⛔",
    color: "#DC143C",
    description: "An error in reasoning or flaw in an argument's logic.",
    prompt: "What logical fallacy is this?",
    placeholder: "This is a false dilemma because...",
    terminal: false,
  },
  value: {
    label: "VALUE",
    icon: "⚓",
    color: "#FFD700",
    description: "A fundamental, bedrock belief — intrinsically important.",
    prompt: "What is the bedrock value?",
    placeholder: "Minimize total suffering",
    terminal: true,
  },
  principle: {
    label: "PRINCIPLE",
    icon: "⚖",
    color: "#9ca3af",
    description: "A fundamental rule or guideline for action or reasoning.",
    prompt: "What is the foundational principle?",
    placeholder: "The principle of proportionality",
    terminal: true,
  },
  "epistemic-limit": {
    label: "EPISTEMIC LIMIT",
    icon: "∞",
    color: "#9900cc",
    description: "The boundary of what we know or can know.",
    prompt: "What is the limit of knowledge?",
    placeholder: "We don't know if consciousness is fundamental or emergent",
    terminal: true,
  },
};

// Context-sensitive children: which node types may be added under a given
// parent type. Terminal types map to an empty list. Mirrors the spec's
// "Context-Sensitive Dropdowns" section.
export const ALLOWED_CHILDREN: Record<NodeType, NodeType[]> = {
  question: [
    "position",
    "argument-support",
    "argument-attack",
    "evidence-empirical",
    "evidence-anecdotal",
    "assumption",
    "definition",
    "caveat",
    "clarification",
    "counter-argument",
    "objection",
    "rebuttal",
    "analogy",
    "thought-experiment",
    "related-concept",
    "logical-fallacy",
  ],
  position: [
    "argument-support",
    "argument-attack",
    "evidence-empirical",
    "evidence-anecdotal",
    "assumption",
    "definition",
    "caveat",
    "clarification",
    "counter-argument",
    "objection",
    "rebuttal",
    "analogy",
    "thought-experiment",
    "related-concept",
    "logical-fallacy",
  ],
  "argument-support": [
    "question",
    "evidence-empirical",
    "evidence-anecdotal",
    "assumption",
    "definition",
    "caveat",
    "clarification",
    "objection",
    "rebuttal",
    "analogy",
    "thought-experiment",
    "related-concept",
    "logical-fallacy",
    "value",
    "principle",
    "epistemic-limit",
  ],
  "argument-attack": [
    "question",
    "evidence-empirical",
    "evidence-anecdotal",
    "assumption",
    "definition",
    "caveat",
    "clarification",
    "objection",
    "rebuttal",
    "analogy",
    "thought-experiment",
    "related-concept",
    "logical-fallacy",
    "value",
    "principle",
    "epistemic-limit",
  ],
  "evidence-empirical": ["objection", "counter-argument", "related-concept"],
  "evidence-anecdotal": ["objection", "counter-argument", "related-concept"],
  assumption: ["objection", "counter-argument", "definition", "related-concept"],
  definition: ["objection", "counter-argument", "related-concept"],
  caveat: ["objection", "counter-argument", "related-concept"],
  clarification: ["objection", "counter-argument", "related-concept"],
  "counter-argument": ["rebuttal", "counter-argument", "related-concept"],
  objection: ["rebuttal", "counter-argument", "related-concept"],
  rebuttal: ["objection", "counter-argument", "related-concept"],
  analogy: [
    "objection",
    "counter-argument",
    "related-concept",
    "logical-fallacy",
  ],
  "thought-experiment": [
    "objection",
    "counter-argument",
    "related-concept",
    "logical-fallacy",
  ],
  "related-concept": ["objection", "counter-argument", "related-concept"],
  "logical-fallacy": ["rebuttal", "counter-argument", "related-concept"],
  value: [],
  principle: [],
  "epistemic-limit": [],
};

// Display order for the Legend panel.
export const NODE_ORDER: NodeType[] = [
  "question",
  "position",
  "argument-support",
  "argument-attack",
  "evidence-empirical",
  "evidence-anecdotal",
  "assumption",
  "definition",
  "caveat",
  "clarification",
  "counter-argument",
  "objection",
  "rebuttal",
  "analogy",
  "thought-experiment",
  "related-concept",
  "logical-fallacy",
  "value",
  "principle",
  "epistemic-limit",
];
